codecov:
  branch: main # Replace with your default branch name, if different

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
